// src/screens/practice/N400PracticeHomeScreen.tsx// src/screens/practice/N400PracticeHomeScreen.tsx





















































































































































































































































































































































export default N400PracticeHomeScreen;});  },    flex: 1,    fontWeight: '500',    lineHeight: 18,    color: '#78350F',    fontSize: 12,  tipText: {  },    lineHeight: 20,    fontWeight: '700',    fontSize: 16,    color: '#F59E0B',  tipBullet: {  },    marginBottom: 8,    gap: 8,    alignItems: 'flex-start',    flexDirection: 'row',  tipItem: {  },    marginBottom: 12,    color: '#92400E',    fontWeight: '700',    fontSize: 14,  tipsTitle: {  },    borderLeftColor: '#F59E0B',    borderLeftWidth: 4,    padding: 20,    borderRadius: 16,  tipsCard: {  },    color: 'white',    fontWeight: '700',    fontSize: 16,  allSectionsText: {  },    paddingHorizontal: 24,    paddingVertical: 16,    gap: 10,    justifyContent: 'center',    alignItems: 'center',    flexDirection: 'row',  allSectionsGradient: {  },    overflow: 'hidden',    borderRadius: 16,    marginBottom: 24,  allSectionsButton: {  },    textAlign: 'center',    fontWeight: '500',    color: '#718096',    fontSize: 11,  cardSubtitle: {  },    marginBottom: 4,    textAlign: 'center',    color: '#1A202C',    fontWeight: '700',    fontSize: 14,  cardTitle: {  },    marginBottom: 10,    justifyContent: 'center',    alignItems: 'center',    borderRadius: 16,    height: 56,    width: 56,  sectionIconContainer: {  },    }),      },        elevation: 4,      android: {      },        shadowRadius: 16,        shadowOpacity: 0.06,        shadowOffset: { width: 0, height: 4 },        shadowColor: '#000',      ios: {    ...Platform.select({    justifyContent: 'center',    minHeight: 130,    alignItems: 'center',    padding: 16,    borderRadius: 20,    backgroundColor: 'white',    width: '48%',  sectionCard: {  },    marginBottom: 20,    gap: 12,    flexWrap: 'wrap',    flexDirection: 'row',  sectionsGrid: {  },    color: '#1A202C',    fontWeight: '700',    fontSize: 16,  sectionTitle: {  },    marginBottom: 16,    gap: 8,    alignItems: 'center',    flexDirection: 'row',  sectionHeader: {  },    fontWeight: '500',    lineHeight: 20,    color: '#1E3A8A',    fontSize: 13,    flex: 1,  infoText: {  },    borderLeftColor: '#1E40AF',    borderLeftWidth: 4,    marginBottom: 24,    alignItems: 'flex-start',    gap: 12,    flexDirection: 'row',    padding: 16,    borderRadius: 16,  infoCard: {  },    paddingBottom: 40,    paddingTop: 20,    paddingHorizontal: 20,  scrollContent: {  },    flex: 1,  container: {  },    marginTop: 1,    color: 'rgba(255,255,255,0.8)',    fontWeight: '500',    fontSize: 12,  headerSubtitle: {  },    color: 'white',    fontWeight: '700',    fontSize: 18,  headerTitle: {  },    flex: 1,    alignItems: 'center',  headerTitleContainer: {  },    justifyContent: 'center',    alignItems: 'center',    backgroundColor: 'rgba(255,255,255,0.2)',    borderRadius: 22,    height: 44,    width: 44,  backButton: {  },    alignItems: 'center',    justifyContent: 'space-between',    flexDirection: 'row',  headerContent: {  },    paddingBottom: 14,    paddingHorizontal: 20,  header: {  },    backgroundColor: '#1E3A8A',  headerContainer: {  },    backgroundColor: '#F8FAFC',    flex: 1,  safeArea: {const styles = StyleSheet.create({};  );    </View>      </ScrollView>        </LinearGradient>          </View>            </Text>              Responde con oraciones completas y de manera clara            <Text style={styles.tipText}>            <Text style={styles.tipBullet}>✓</Text>          <View style={styles.tipItem}>          </View>            </Text>              Cada pregunta puede hacerse de diferentes maneras — practica las variaciones            <Text style={styles.tipText}>            <Text style={styles.tipBullet}>✓</Text>          <View style={styles.tipItem}>          </View>            <Text style={styles.tipText}>Escucha el audio y practica respondiendo en voz alta</Text>            <Text style={styles.tipBullet}>✓</Text>          <View style={styles.tipItem}>          <Text style={styles.tipsTitle}>💡 Consejos</Text>        >          style={styles.tipsCard}          colors={['#FEF3C7', '#FDE68A'] as [string, string]}        <LinearGradient        {/* Tips */}        </TouchableOpacity>          </LinearGradient>            </Text>              Practicar todas ({n400Questions.length} preguntas)            <Text style={styles.allSectionsText}>            <MaterialCommunityIcons name="play-circle" size={24} color="white" />          >            style={styles.allSectionsGradient}            end={{ x: 1, y: 0 }}            start={{ x: 0, y: 0 }}            colors={['#1E40AF', '#3B82F6'] as [string, string]}          <LinearGradient        >          activeOpacity={0.85}          }            })              sectionTitle: 'Todas las secciones',              sectionKey: 'all',              sectionId: 'all',            navigation.navigate('N400SectionPractice' as any, {          onPress={() =>          style={styles.allSectionsButton}        <TouchableOpacity        {/* All Sections Button */}        </View>          })}            );              </TouchableOpacity>                </Text>                  {count} {count === 1 ? 'pregunta' : 'preguntas'}                <Text style={styles.cardSubtitle}>                <Text style={styles.cardTitle}>{section.titleEs}</Text>                </View>                  />                    color={section.color}                    size={28}                    name={section.icon as any}                  <MaterialCommunityIcons                <View style={[styles.sectionIconContainer, { backgroundColor: section.color + '15' }]}>              >                activeOpacity={0.85}                onPress={() => handleSectionPress(section)}                style={styles.sectionCard}                key={section.id}              <TouchableOpacity            return (            const count = getQuestionCount(section);          {n400Sections.map((section) => {        <View style={styles.sectionsGrid}>        {/* Sections Grid */}        </View>          <Text style={styles.sectionTitle}>Secciones del N-400</Text>          <MaterialCommunityIcons name="format-list-bulleted" size={18} color="#1E40AF" />        <View style={styles.sectionHeader}>        {/* Section Header */}        </LinearGradient>          </Text>            de ciudadanía, basadas en el formulario N-400.            Practica las preguntas que un oficial de USCIS te hará durante la entrevista          <Text style={styles.infoText}>          <MaterialCommunityIcons name="information" size={20} color="#1E40AF" />        >          style={styles.infoCard}          colors={['#EFF6FF', '#DBEAFE'] as [string, string]}        <LinearGradient        {/* Info Card */}      >        showsVerticalScrollIndicator={false}        contentContainerStyle={styles.scrollContent}        style={styles.container}      <ScrollView      </View>        </LinearGradient>          </View>            <View style={{ width: 44 }} />            </View>              <Text style={styles.headerSubtitle}>Práctica por sección</Text>              <Text style={styles.headerTitle}>Formulario N-400</Text>            <View style={styles.headerTitleContainer}>            </TouchableOpacity>              <MaterialCommunityIcons name="arrow-left" size={24} color="white" />            <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>          <View style={styles.headerContent}>        >          style={[styles.header, { paddingTop: insets.top + 8 }]}          end={{ x: 1, y: 1 }}          start={{ x: 0, y: 0 }}          colors={['#1E3A8A', '#1E40AF', '#3B82F6'] as [string, string, string]}        <LinearGradient      <View style={styles.headerContainer}>      {/* Header */}      <StatusBar barStyle="light-content" translucent backgroundColor="transparent" />    <View style={styles.safeArea}>  return (  };    });      sectionTitle: section.titleEs,      sectionKey: section.key,      sectionId: section.id,    navigation.navigate('N400SectionPractice' as any, {  const handleSectionPress = (section: N400SectionInfo) => {    n400Questions.filter((q) => q.section === section.id).length;  const getQuestionCount = (section: N400SectionInfo) =>  const insets = useSafeAreaInsets();  const navigation = useNavigation<NavigationProps>();const N400PracticeHomeScreen = () => {} from '../../data/n400FormPractice';  N400SectionInfo,  n400Questions,  n400Sections,import {import { NavigationProps } from '../../types/navigation';import { useSafeAreaInsets } from 'react-native-safe-area-context';import { LinearGradient } from 'expo-linear-gradient';import { MaterialCommunityIcons } from '@expo/vector-icons';import { useNavigation } from '@react-navigation/native';} from 'react-native';  Platform,  StatusBar,  ScrollView,  TouchableOpacity,  Text,  StyleSheet,  View,import {import React from 'react';

























































































































































































































































































































































































































































});  },    marginTop: 2,    color: '#64748B',    fontSize: 12,  extraSub: {  },    color: '#1E293B',    fontWeight: '600',    fontSize: 15,  extraTitle: {  },    marginLeft: 12,    flex: 1,  extraInfo: {  },    justifyContent: 'center',    alignItems: 'center',    borderRadius: 12,    height: 44,    width: 44,  extraIcon: {  },    elevation: 2,    shadowRadius: 3,    shadowOpacity: 0.05,    shadowOffset: { width: 0, height: 1 },    shadowColor: '#000',    marginBottom: 10,    padding: 14,    borderRadius: 14,    backgroundColor: '#FFFFFF',    alignItems: 'center',    flexDirection: 'row',  extraCard: {  },    textAlign: 'right',    marginTop: 4,    color: 'rgba(255,255,255,0.8)',    fontSize: 11,  progressText: {  },    borderRadius: 2,    backgroundColor: '#FFFFFF',    height: '100%',  progressFill: {  },    overflow: 'hidden',    borderRadius: 2,    backgroundColor: 'rgba(255,255,255,0.3)',    height: 4,  progressBar: {  },    marginBottom: 8,    color: 'rgba(255,255,255,0.8)',    fontSize: 12,  cardQuestions: {  },    marginBottom: 4,    color: '#FFFFFF',    fontWeight: '700',    fontSize: 15,  cardTitle: {  },    color: '#FFFFFF',    fontWeight: '600',    fontSize: 10,  variationsText: {  },    paddingVertical: 3,    paddingHorizontal: 8,    borderRadius: 8,    backgroundColor: 'rgba(255,255,255,0.25)',  variationsBadge: {  },    justifyContent: 'center',    alignItems: 'center',    backgroundColor: 'rgba(255,255,255,0.2)',    borderRadius: 22,    height: 44,    width: 44,  iconCircle: {  },    marginBottom: 10,    alignItems: 'flex-start',    justifyContent: 'space-between',    flexDirection: 'row',  cardIconRow: {  },    justifyContent: 'space-between',    minHeight: 160,    padding: 14,    borderRadius: 16,  categoryCard: {  },    width: CARD_WIDTH,  gridItem: {  },    marginBottom: 24,    gap: 12,    flexWrap: 'wrap',    flexDirection: 'row',  grid: {  },    marginBottom: 14,    color: '#1E293B',    fontWeight: '700',    fontSize: 17,  sectionTitle: {  },    marginTop: 2,    color: 'rgba(255,255,255,0.8)',    fontSize: 12,  quickRoundSub: {  },    color: '#FFFFFF',    fontWeight: '700',    fontSize: 17,  quickRoundTitle: {  },    flex: 1,    alignItems: 'center',    flexDirection: 'row',  quickRoundLeft: {  },    marginBottom: 24,    padding: 16,    borderRadius: 16,    justifyContent: 'space-between',    alignItems: 'center',    flexDirection: 'row',  quickRoundCard: {  },    lineHeight: 19,    color: '#1E40AF',    fontSize: 13,    flex: 1,  introText: {  },    alignItems: 'flex-start',    gap: 10,    marginBottom: 16,    padding: 14,    borderRadius: 14,    backgroundColor: '#EEF2FF',    flexDirection: 'row',  introCard: {  },    padding: 20,  contentContainer: {  },    flex: 1,  content: {  },    marginTop: 2,    color: 'rgba(255,255,255,0.7)',    fontSize: 11,  statLabel: {  },    color: '#FFFFFF',    fontWeight: '700',    fontSize: 20,  statValue: {  },    alignItems: 'center',  statBadge: {  },    paddingHorizontal: 8,    paddingVertical: 12,    borderRadius: 14,    backgroundColor: 'rgba(255,255,255,0.12)',    justifyContent: 'space-around',    flexDirection: 'row',  headerStats: {  },    marginTop: 2,    color: 'rgba(255,255,255,0.7)',    fontSize: 13,  headerSubtitle: {  },    color: '#FFFFFF',    fontWeight: '700',    fontSize: 20,  headerTitle: {  },    alignItems: 'center',  headerCenter: {  },    justifyContent: 'center',    alignItems: 'center',    backgroundColor: 'rgba(255,255,255,0.15)',    borderRadius: 18,    height: 36,    width: 36,  backButton: {  },    marginBottom: 16,    justifyContent: 'space-between',    alignItems: 'center',    flexDirection: 'row',  headerRow: {  },    paddingHorizontal: 20,    paddingBottom: 20,  header: {  },    backgroundColor: '#F1F5F9',    flex: 1,  safeArea: {const styles = StyleSheet.create({export default N400PracticeHomeScreen;};  );    </View>      </ScrollView>        <View style={{ height: 40 }} />        </TouchableOpacity>          <MaterialCommunityIcons name="chevron-right" size={22} color="#94A3B8" />          </View>            </Text>              {n400Definitions.length} términos clave del N-400            <Text style={styles.extraSub}>            <Text style={styles.extraTitle}>Vocabulario Difícil</Text>          <View style={styles.extraInfo}>          </View>            <MaterialCommunityIcons name="book-open-variant" size={24} color="#D97706" />          <View style={[styles.extraIcon, { backgroundColor: '#FEF3C7' }]}>        <TouchableOpacity activeOpacity={0.8} onPress={handleDefinitions} style={styles.extraCard}>        </TouchableOpacity>          <MaterialCommunityIcons name="chevron-right" size={22} color="#94A3B8" />          </View>            </Text>              {n400Protocol.length} frases: juramento, documentos, transiciones            <Text style={styles.extraSub}>            <Text style={styles.extraTitle}>Protocolo de Entrevista</Text>          <View style={styles.extraInfo}>          </View>            <MaterialCommunityIcons name="hand-wave" size={24} color="#1E40AF" />          <View style={[styles.extraIcon, { backgroundColor: '#EEF2FF' }]}>        <TouchableOpacity activeOpacity={0.8} onPress={handleProtocol} style={styles.extraCard}>        <Text style={styles.sectionTitle}>Extras</Text>        {/* Extra sections */}        </View>          })}            );              </TouchableOpacity>                </LinearGradient>                  </Text>                    {completed}/{total}                  <Text style={styles.progressText}>                  </View>                    <View style={[styles.progressFill, { width: `${pct}%` }]} />                  <View style={styles.progressBar}>                  {/* Progress bar */}                  <Text style={styles.cardQuestions}>{total} preguntas</Text>                  <Text style={styles.cardTitle} numberOfLines={2}>{cat.title}</Text>                  </View>                    </View>                      </Text>                        {cat.questions.reduce((s, q) => s + q.variations.length, 0)} vars                      <Text style={styles.variationsText}>                    <View style={styles.variationsBadge}>                    </View>                      />                        color="#FFFFFF"                        size={24}                        name={cat.icon as any}                      <MaterialCommunityIcons                    <View style={styles.iconCircle}>                  <View style={styles.cardIconRow}>                >                  style={styles.categoryCard}                  end={{ x: 1, y: 1 }}                  start={{ x: 0, y: 0 }}                  colors={cat.gradient as [string, string]}                <LinearGradient              >                style={styles.gridItem}                onPress={() => handleCategoryPress(cat.id)}                activeOpacity={0.8}                key={cat.id}              <TouchableOpacity            return (            const pct = total > 0 ? (completed / total) * 100 : 0;            const total = cat.questions.length;            const completed = progress[cat.id] || 0;          {n400Categories.map((cat) => {        <View style={styles.grid}>        {/* Category grid */}        <Text style={styles.sectionTitle}>Secciones del N-400</Text>        {/* Section title */}        </TouchableOpacity>          </LinearGradient>            <MaterialCommunityIcons name="chevron-right" size={24} color="#FFFFFF" />            </View>              </View>                <Text style={styles.quickRoundSub}>20 preguntas al azar de todas las categorías</Text>                <Text style={styles.quickRoundTitle}>Ronda Rápida</Text>              <View style={{ marginLeft: 12 }}>              <MaterialCommunityIcons name="lightning-bolt" size={28} color="#FFFFFF" />            <View style={styles.quickRoundLeft}>          >            style={styles.quickRoundCard}            end={{ x: 1, y: 0 }}            start={{ x: 0, y: 0 }}            colors={['#F59E0B', '#D97706'] as [string, string]}          <LinearGradient        <TouchableOpacity activeOpacity={0.8} onPress={handleQuickRound}>        {/* Quick Round button */}        </View>          </Text>            entender y responder cada sección.            El oficial de USCIS te hará preguntas sobre tu formulario N-400. Aquí practicarás           <Text style={styles.introText}>          <MaterialCommunityIcons name="information-outline" size={22} color="#1E40AF" />        <View style={styles.introCard}>        {/* Intro card */}      >        showsVerticalScrollIndicator={false}        contentContainerStyle={styles.contentContainer}        style={styles.content}      <ScrollView      </LinearGradient>        </View>          </View>            <Text style={styles.statLabel}>Completadas</Text>            <Text style={styles.statValue}>{totalCompleted}</Text>          <View style={styles.statBadge}>          </View>            <Text style={styles.statLabel}>Variaciones</Text>            <Text style={styles.statValue}>{TOTAL_N400_VARIATIONS}</Text>          <View style={styles.statBadge}>          </View>            <Text style={styles.statLabel}>Preguntas</Text>            <Text style={styles.statValue}>{TOTAL_N400_QUESTIONS}</Text>          <View style={styles.statBadge}>        <View style={styles.headerStats}>        {/* Progress summary */}        </View>          <View style={{ width: 36 }} />          </View>            <Text style={styles.headerSubtitle}>Formulario de Naturalización</Text>            <Text style={styles.headerTitle}>Práctica N-400</Text>          <View style={styles.headerCenter}>          </TouchableOpacity>            <MaterialCommunityIcons name="arrow-left" size={24} color="#FFFFFF" />          >            hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}            style={styles.backButton}            onPress={() => navigation.goBack()}          <TouchableOpacity        <View style={styles.headerRow}>      >        style={[styles.header, { paddingTop: insets.top + 8 }]}        end={{ x: 1, y: 1 }}        start={{ x: 0, y: 0 }}        colors={['#1E3A8A', '#1E40AF', '#3B82F6'] as [string, string, string]}      <LinearGradient      {/* Header */}      <StatusBar barStyle="light-content" translucent backgroundColor="transparent" />    <View style={styles.safeArea}>  return (  };    navigation.navigate('N400SectionPractice', { categoryId: 'definitions', mode: 'study' });  const handleDefinitions = () => {  };    navigation.navigate('N400SectionPractice', { categoryId: 'protocol', mode: 'study' });  const handleProtocol = () => {  };    navigation.navigate('N400SectionPractice', { categoryId: 'all', mode: 'quick' });  const handleQuickRound = () => {  };    navigation.navigate('N400SectionPractice', { categoryId, mode: 'study' });  const handleCategoryPress = (categoryId: string) => {  const totalCompleted = Object.values(progress).reduce((s, v) => s + v, 0);  );    }, [loadProgress])      loadProgress();    useCallback(() => {  useFocusEffect(  }, []);    }      // silently ignore    } catch {      if (raw) setProgress(JSON.parse(raw));      const raw = await AsyncStorage.getItem('@n400:progress');    try {  const loadProgress = useCallback(async () => {  const [progress, setProgress] = useState<{ [catId: string]: number }>({});  const insets = useSafeAreaInsets();  const navigation = useNavigation<any>();const N400PracticeHomeScreen = () => {const CARD_WIDTH = (width - 48 - 12) / 2;const { width } = Dimensions.get('window');} from '../../data/n400FormPractice';  TOTAL_N400_VARIATIONS,  TOTAL_N400_QUESTIONS,  n400Definitions,  n400Protocol,  n400Categories,import {import AsyncStorage from '@react-native-async-storage/async-storage';import { LinearGradient } from 'expo-linear-gradient';import { MaterialCommunityIcons } from '@expo/vector-icons';import { useSafeAreaInsets } from 'react-native-safe-area-context';import { useNavigation, useFocusEffect } from '@react-navigation/native';} from 'react-native';  Dimensions,  StatusBar,  ScrollView,  TouchableOpacity,  Text,  StyleSheet,  View,import {import React, { useState, useCallback } from 'react';